const Allocator = std.mem.Allocator;
const c = @import("c.zig").ncurses;

pub const chtype = c_uint;
pub const mmask_t = c_uint;
pub const attr_t = chtype;

const Err = c.ERR; // -1
const Ok = c.OK; // 0

pub const cchar_t = extern struct {
    attr: attr_t,
    chars: [CCHARW_MAX]wchar_t,
};

// zig fmt: off
pub const Color = extern enum(u8) {
    black   = 0,
    red     = 1,
    green   = 2,
    yellow  = 3,
    blue    = 4,
    magenta = 5,
    cyan    = 6,
    white   = 7,
};
// zig fmt: on

// zig fmt: off
pub const Key = extern enum(c_int) {
    //  Pseudo-character tokens outside ASCII range.  The curses wgetch() function
    //  will return any given one of these only if the corresponding k- capability
    //  is defined in your terminal's terminfo entry.
    //
    //  Some keys (KEY_A1, etc) are arranged like this:
    //     a1     up    a3
    //     left   b2    right
    //     c1     down  c3
    //
    //  A few key codes do not depend upon the terminfo entry.

    code_yes   = 0o400, // A wchar_t contains a key code
    min        = 0o401, // Minimum curses key
    @"break"   = 0o401, // Break key (unreliable)
    sreset     = 0o530, // Soft (partial) reset (unreliable)
    reset      = 0o531, // Reset or hard reset (unreliable)

    // These definitions were generated by ./MKkey_defs.sh ./Caps ./Caps-ncurses
    down       = 0o402, // down-arrow key
    up         = 0o403, // up-arrow key
    left       = 0o404, // left-arrow key
    right      = 0o405, // right-arrow key
    home       = 0o406, // home key
    backspace  = 0o407, // backspace key
    f0         = 0o410, // Function keys.  Space for 64
    f1         = 0o411,
    f2         = 0o412,
    f3         = 0o413,
    f4         = 0o414,
    f5         = 0o415,
    f6         = 0o416,
    f7         = 0o417,
    f8         = 0o420,
    f9         = 0o421,
    f10        = 0o422,
    f11        = 0o423,
    f12        = 0o424,
    dl         = 0o510, // delete-line key
    il         = 0o511, // insert-line key
    dc         = 0o512, // delete-character key
    ic         = 0o513, // insert-character key
    eic        = 0o514, // sent by rmir or smir in insert mode
    clear      = 0o515, // clear-screen or erase key
    eos        = 0o516, // clear-to-end-of-screen key
    eol        = 0o517, // clear-to-end-of-line key
    sf         = 0o520, // scroll-forward key
    sr         = 0o521, // scroll-backward key
    npage      = 0o522, // next-page key
    ppage      = 0o523, // previous-page key
    stab       = 0o524, // set-tab key
    ctab       = 0o525, // clear-tab key
    catab      = 0o526, // clear-all-tabs key
    enter      = 0o527, // enter/send key
    print      = 0o532, // print key
    ll         = 0o533, // lower-left key (home down)
    a1         = 0o534, // upper left of keypad
    a3         = 0o535, // upper right of keypad
    b2         = 0o536, // center of keypad
    c1         = 0o537, // lower left of keypad
    c3         = 0o540, // lower right of keypad
    btab       = 0o541, // back-tab key
    beg        = 0o542, // begin key
    cancel     = 0o543, // cancel key
    close      = 0o544, // close key
    command    = 0o545, // command key
    copy       = 0o546, // copy key
    create     = 0o547, // create key
    end        = 0o550, // end key
    exit       = 0o551, // exit key
    find       = 0o552, // find key
    help       = 0o553, // help key
    mark       = 0o554, // mark key
    message    = 0o555, // message key
    move       = 0o556, // move key
    next       = 0o557, // next key
    open       = 0o560, // open key
    options    = 0o561, // options key
    previous   = 0o562, // previous key
    redo       = 0o563, // redo key
    reference  = 0o564, // reference key
    refresh    = 0o565, // refresh key
    replace    = 0o566, // replace key
    restart    = 0o567, // restart key
    @"resume"  = 0o570, // resume key
    save       = 0o571, // save key
    sbeg       = 0o572, // shifted begin key
    scancel    = 0o573, // shifted cancel key
    scommand   = 0o574, // shifted command key
    scopy      = 0o575, // shifted copy key
    screate    = 0o576, // shifted create key
    sdc        = 0o577, // shifted delete-character key
    sdl        = 0o600, // shifted delete-line key
    select     = 0o601, // select key
    send       = 0o602, // shifted end key
    seol       = 0o603, // shifted clear-to-end-of-line key
    sexit      = 0o604, // shifted exit key
    sfind      = 0o605, // shifted find key
    shelp      = 0o606, // shifted help key
    shome      = 0o607, // shifted home key
    sic        = 0o610, // shifted insert-character key
    sleft      = 0o611, // shifted left-arrow key
    smessage   = 0o612, // shifted message key
    smove      = 0o613, // shifted move key
    snext      = 0o614, // shifted next key
    soptions   = 0o615, // shifted options key
    sprevious  = 0o616, // shifted previous key
    sprint     = 0o617, // shifted print key
    sredo      = 0o620, // shifted redo key
    sreplace   = 0o621, // shifted replace key
    sright     = 0o622, // shifted right-arrow key
    srsume     = 0o623, // shifted resume key
    ssave      = 0o624, // shifted save key
    ssuspend   = 0o625, // shifted suspend key
    sundo      = 0o626, // shifted undo key
    @"suspend" = 0o627, // suspend key
    undo       = 0o630, // undo key
    mouse      = 0o631, // Mouse event has occurred
    resize     = 0o632, // Terminal resize event
    event      = 0o633, // We were interrupted by an event
    max        = 0o777, // Maximum key value is 0633

    _,                  // Any other key
};
// zig fmt: on

// zig fmt: off
pub const Attribute = extern enum(u32) {
    fn ncurses_bits(mask: u32, shift: u5) u32 {
        const default_shift: u5 = 8;
        return mask << default_shift + shift;
    }

    normal     = 0,
    attributes = ncurses_bits(1, 0),
    chartext   = ncurses_bits(1, 0) - 1,
    color      = ncurses_bits((1 << 8) - 1, 0),
    standout   = ncurses_bits(1, 8),
    underline  = ncurses_bits(1, 9),
    reverse    = ncurses_bits(1, 10),
    blink      = ncurses_bits(1, 11),
    dim        = ncurses_bits(1, 12),
    bold       = ncurses_bits(1, 13),
    altcharset = ncurses_bits(1, 14),
    invis      = ncurses_bits(1, 15),
    protect    = ncurses_bits(1, 16),
    horizontal = ncurses_bits(1, 17),
    left       = ncurses_bits(1, 18),
    low        = ncurses_bits(1, 19),
    right      = ncurses_bits(1, 20),
    top        = ncurses_bits(1, 21),
    vertical   = ncurses_bits(1, 22),
    italic     = ncurses_bits(1, 23),
};
// zig fmt: on

pub const NcursesError = error{
    Generic,
};

pub extern "ncurses" var stdscr: *c._win_st;

pub const Window = struct {
    ptr: *c._win_st,

    pub fn default() Window {
        return Window{ .ptr = stdscr };
    }

    //====================================================================
    // Initialization and manipulation
    //====================================================================

    pub fn initscr() Window {
        return Window{ .ptr = c.initscr() };
    }
    pub fn endwin() !void {
        if (c.endwin() == Err) return NcursesError.Generic;
    }

    //====================================================================
    // Printing
    //====================================================================

    pub fn wprintw(self: Window, comptime format: [*:0]const u8, args: anytype) !void {
        if (@call(.{}, c.printw, .{ self.ptr, format } ++ args) != Ok) return NcursesError.Generic;
    }

    pub fn wgetch(self: Window) !c_int {
        const result = c.wgetch(self.ptr);
        if (result == Err) return NcursesError.Generic;

        return result;
    }
};

//====================================================================
// Printing
//====================================================================

pub fn printw(comptime format: [*:0]const u8, args: anytype) !void {
    if (@call(.{}, c.printw, .{format} ++ args) != Ok) return NcursesError.Generic;
}
pub fn getch() !c_int {
    const result = c.getch();
    if (result == Err) return NcursesError.Generic;

    return result;
}

//====================================================================
// Input options
//====================================================================

pub fn cbreak() !void {
    if (c.cbreak() == Err) return NcursesError.Generic;
}
pub fn nocbreak() !void {
    if (c.nocbreak() == Err) return NcursesError.Generic;
}
pub fn echo() !void {
    if (c.echo() == Err) return NcursesError.Generic;
}
pub fn noecho() !void {
    if (c.noecho() == Err) return NcursesError.Generic;
}
pub fn raw() !void {
    if (c.raw() == Err) return NcursesError.Generic;
}
pub fn noraw() !void {
    if (c.noraw() == Err) return NcursesError.Generic;
}
pub fn keypad(self: Window, bf: bool) !void {
    if (c.keypad(self.ptr, bf) == Err) return NcursesError.Generic;
}

//====================================================================
// Character and window attribute control
//====================================================================

pub fn attron(attrs: c_int) !void {
    if (c.attron(attrs) == Err) return NcursesError.Generic;
}
pub fn attroff(attrs: c_int) !void {
    if (c.attron(attrs) == Err) return NcursesError.Generic;
}

//====================================================================
// Refresh windows and lines
//====================================================================

pub fn refresh() !void {
    if (c.refresh() == Err) return NcursesError.Generic;
}
